In [81]:

import duckdb
import pandas as pd

In [ ]:
sql = '''
show tables
'''

with duckdb.connect('data/parking_violations.db') as con:
    display(con.sql(sql).df())

Empty DataFrame
Columns: [name]
Index: []

In [ ]:
sql = '''
show tables

'''

with duckdb.connect('data/parking_violations.db') as con:
    display(con.sql(sql).df())

Empty DataFrame
Columns: [name]
Index: []

In [84]:
sql_query1 = ''' 
    CREATE OR REPLACE TABLE parking_violations AS
    SELECT * 
    FROM read_csv_auto('data/dof_parking_violation_codes.csv',
    normalize_names=True
    )
'''

sql_query2 = ''' 
    CREATE OR REPLACE TABLE parking_violations_2023 AS
    SELECT * 
    FROM read_csv_auto('data/parking_violations_issued_fiscal_year_2023_sample.csv',
    normalize_names=True
    )
'''

with duckdb.connect('data/parking_violations.db') as con:
    con.sql(sql_query1)
    con.sql(sql_query2)

In [85]:
sql_query1 = ''' 
    CREATE OR REPLACE TABLE parking_violations AS
    SELECT * 
    FROM read_csv_auto('data/dof_parking_violation_codes.csv',
    normalize_names=True
    )
'''

sql_query2 = ''' 
    CREATE OR REPLACE TABLE parking_violations_2023 AS
    SELECT * 
    FROM read_csv_auto('data/parking_violations_issued_fiscal_year_2023_sample.csv',
    normalize_names=True
    )
'''

with duckdb.connect('data/prod_parking_violations.db') as con:
    con.sql(sql_query1)
    con.sql(sql_query2)

In [86]:
sql = '''
show tables
'''

with duckdb.connect('data/prod_parking_violations.db') as con:
    display(con.sql(sql).df())

                      name
0       parking_violations
1  parking_violations_2023